name: CI-macOS

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-and-test-macOS:
    runs-on: macos-15
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Swift version
        run: swift --version

      - name: Build WordFeature
        run: swift build --package-path WordFeature

      - name: Test WordAPI
        run: swift test --package-path WordAPI

      - name: Test WordCache
        run: swift test --package-path WordCache

      - name: Test WordCacheInfrastructure
        run: swift test --package-path WordCacheInfrastructure
