name: Xcode Cloud Test macOS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [xcc-test-macos]

jobs:
  test-macos-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "macOS tests finished from Xcode Cloud"
